### ISSUE TITLE
Using different accounts in secret references

### ISSUE THREAD

**Issue by shadi-sharaf-nuk** [benvp/insomnia-plugin-op#4]
In the placeholder for the field reference, it references the syntax for choosing an account name within the references, see https://github.com/benvp/insomnia-plugin-op/blob/main/src/app.ts#L25

I don't think this is currently working, as the OP CLI needs a flag to be sent with the account id, instead of including it in the references.

So I think we can do either one of two solutions:
- Add a new account dropdown
- Support the syntax from the placeholder, but parse it in the plugin and if an account is found, use the flag with the CLI call instead of sending the reference as is.

Happy to PR the latter which seems like a more straight-forward solution.

**Comment by shadyvb** [comment]
Ended up adding the account field (text, not dropdown), PR sent!
